### ISSUE TITLE
Create acceptance criteria

### ISSUE THREAD

**Issue by robertpdavis** [robertpdavis/dark-crawler#33]

**Comment by umairkhalid** [comment]
GIVEN a CMS-style board game
WHEN I visit the site for the first time
THEN I am presented with the homepage, which includes name of the game; navigation links for the main page.
WHEN I click on the main page link
THEN I am prompted to either sign up or sign in
WHEN I choose to sign up
THEN I am prompted to create a username, email and password
WHEN I click on the sign-up button
THEN my user credentials are saved and I am logged into the site
WHEN I revisit the site at a later time and choose to sign in
THEN I am prompted to enter my email and password
WHEN I am signed in to the site
THEN I am taken to the welcome page which includes option to start a new game or continue the existing game; navigation links for the homepage and the dashboard; and the option to log out
WHEN I click on the new game option
THEN I am taken to the character selection screen
WHEN I select the character option
THEN I am taken to the game page which displays current character abilities, and option to make the next move or finish the game; navigation links for the homepage and dashboard; and the option to logout
WHEN I click on the make a move option
THEN the user pointer moves to the next available tile on the game grid, which includes encounter points and/or reward prize
WHEN the user pointer comes across encounter or reward
THEN the character abilities reflect the value of that encounter or reward and displays on the screen
WHEN I click on finish the game
THEN I am taken back to the welcome screen with options to start a new game or continue the game
WHEN I click on the logout option in the navigation
THEN I am signed out of the site
WHEN I am idle on the site for more than a set time
THEN I am prompted to log in again before I can play the game
